session "TopA" = HOL +
  theories
    BasicInvariants
    BuggyRules
    CoherenceProperties
    Transposed
    FixInvalidLoad
    FixSharedLoad
    FixInvalidStore
    FixSharedStore
    FixSharedEvict
    FixModifiedEvict
    FixSharedSnpInv
    FixISDSnpInv
    FixISDData
    FixISDIData
    FixIMADData
    FixISADData
    FixIMADGO
    FixSMADData
    FixISADGO
    FixSMADGO
    FixSMAGO
    FixSMADSnpInv
    FixSMDData
    FixIMAGO
    FixISAGO
    FixModifiedStore
    FixModifiedLoad
    FixSIAGO_WritePull
    FixSIAGO_WritePullDrop
    FixIIAGO_WritePull
    FixIIAGO_WritePullDrop
    FixIMDData
    FixMIASnpDataInvalid
    FixMIASnpDataShared
    FixMIASnpInv
    FixMIAGO_WritePull
    FixSIASnpInv
    FixModifiedSnpInv
    FixModifiedSnpDataShared
    FixModifiedSnpDataInvalid
    FixModifiedDirtyEvict
    FixInvalidRdShared
    FixInvalidRdOwn
    FixSharedRdShared
    FixShared_CleanEvict_NotLastData
    FixShared_CleanEvict_NotLastDrop
    FixShared_CleanEvict_Last
    FixShared_CleanEvictNoData_Last
    FixShared_CleanEvictNoData_NotLast
    FixSharedDirtyEvict
    FixModifiedDirtyEvict
    FixModifiedRdShared
    FixModifiedRdOwn
    FixSharedRdOwn
    FixSharedRdOwnSelf
    FixSDData
    FixSADData
    FixMDData
    FixIDData
    FixMADData
    FixSADRspIFwdM
    FixSADRspSFwdM
    FixMADRspIFwdM
    FixMARspIFwdM
    FixSARspIFwdM
    FixSARspSFwdM
    FixSBData
    FixIBData
    FixMBData
    FixInvalidDirtyEvict
    FixMARspIHitSE
    FixSIACGO